### ISSUE TITLE
Aktualizacja zadań rekrutacyjnych

### ISSUE THREAD

**Issue by czana** [Selleo/washing-machine-lite#42]
## Short overview
Chcemy zaktualizować narzędzia/paczki dla naszych zadań rekrutacyjnych

## ToDo

Trzeba zmigrować kilka rzeczy:
- [x] CRA => Vite
- [x] JS => TS
- [x] moment.js => date.fns
- [x] redux i obsługa danych lokalnie => TanstackQuery i https://www.npmjs.com/package/json-server albo prosty server node (ale lepiej json-server)
- [x] Dodać Eslint & prettier
- [x] redux-form => react-hook-form

## Notes
Część migracji zrobiona przez Arka M na branchy: `update_repo`

## Contact points
AM/TC
